name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: Description
    attributes:
      label: Is your feature request related to a problem? Please describe. 
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: your_solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        You can attach images and screenshots by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
